### ISSUE TITLE
FailedPreconditionError in the demos

### ISSUE THREAD

**Issue by maximilianmordig** [ICL-SML/Doubly-Stochastic-DGP#10]
When I try to run one of the demos, e.g. the file demo_step_function.ipynb, I get a
FailedPreconditionError
when evaluating the cell right after the text "We'll now use a 2 layer DGP".
It basically says

FailedPreconditionError: Attempting to use uninitialized value beta1_power_2
	 [[Node: beta1_power_2/read = Identity[T=DT_FLOAT, _class=["loc:@DGP-38819a76-130/layers/0/feature/Z/unconstrained"]

beta1_power seems to be a parameter in the Adam optimizer, but I have no idea how all is glued together, so I wonder why the initializer is not run.

**Comment by hughsalimbeni** [comment]
You're using tensorflow 1.6, I expect. GPflow only works with 1.5 for now

**Comment by maximilianmordig** [comment]
Thanks, that actually solved the issue. It is strange because the gpflow github page does not put any comment about it and the setup file requires only a min version of tensorflow1.4. Is there a systematic method to solve these version related issues?

**Comment by hughsalimbeni** [comment]
It's an occupational hazard of working with tensorflow, I fear. But you're absolutely right, gpflow should really say this somewhere as many users are likely to have the up to date tensorflow. I'll open an issue there now.
