### ISSUE TITLE
num_data option is missing from DGP_Base

### ISSUE THREAD

**Issue by Joshuaalbert** [ICL-SML/Doubly-Stochastic-DGP#11]
Minor fix would enable using tensor inputs X and Y and follow the api of gpflow better.
Currently, `num_data` is [grabbed](https://github.com/ICL-SML/Doubly-Stochastic-DGP/blob/master/doubly_stochastic_dgp/dgp.py#L43) from `X.shape[0]` and the change would be `num_data = num_data or X.shape[0]` and add as kwarg.

**Comment by Joshuaalbert** [comment]
Just realized there are other potential break points like https://github.com/ICL-SML/Doubly-Stochastic-DGP/blob/master/doubly_stochastic_dgp/dgp.py#L149

**Comment by hughsalimbeni** [comment]
Agreed. I'm refactoring the code so the user has more control of the layer initializations, so this issue shouldn't be so much of a problem.
