### ISSUE TITLE
Add more dimensions than Dimensions of the problem

### ISSUE THREAD

**Issue by Gonzalo933** [ICL-SML/Doubly-Stochastic-DGP#14]
Hello,

I was wondering if it's possible to add more dimensions to the hidden layers than the dimensions of the problem(D), I see that in all the demos, the first layer always has D dimensions and the other layers either have the same or lower dimensions, I was wondering if its possible to have a configuration like:

[D, 2*D, D]
or
[D, D-1, D]

I tried it, but I get some errors, I think this will be useful to make the model more flexible to low dimension problems.

**Comment by hughsalimbeni** [comment]
Hi sorry for the late reply (I've been at AISTATS). This was possible with the previous code but the upgrade to gpflow1.0 lost the functionality out the box. It should be easy to do though: just adapt the code in the `DGP.__init__` to concat zeros and then pass the layers directly to `DGP_Base`

**Comment by hughsalimbeni** [comment]
Can you try out the PR above and let me know if that works for you?

**Comment by hughsalimbeni** [comment]
Great thanks for that. I'll merge in now
