### ISSUE TITLE
MIMO systems and marginal likelihood

### ISSUE THREAD

**Issue by DiegoRomeres** [ICL-SML/Doubly-Stochastic-DGP#3]
I am trying to do identification of a multi-output system. But I am encountering dimensional problems in the function `_predict_density` at the line `l = tf.reshape(l_flat, [S, N])`. Accordingly to the paper, the algorithm should be able to identify MIMO systems and even if the outputs are assumed to be independent it should be possible to have one likelihood for all the channels rather than estimate one channel at the time.
Is this functionality already considered in the current implementation?

**Comment by hughsalimbeni** [comment]
Hi, Sorry for the delay and thanks for flagging this up. The `predict_density` function is only written for 1D inputs. It's a small change to make it work with multiple dimensional Y. I'll do that asap

**Comment by hughsalimbeni** [comment]
Done. Should work now. Let me know if not. Thanks again for pointing this out
