### ISSUE TITLE
Calculating log-likelihood

### ISSUE THREAD

**Issue by BaoGenzo** [ICL-SML/Doubly-Stochastic-DGP#34]
I see in the demos that for regression problems you are normalizing both y_train and y_test. 

My question is: why, when calculating log likelihood you scale the predictions of the DGP by Y_std??

for example (function asess_sampled, from demo_regression_UCI.ipynb):

`S_lik = np.sum(norm.logpdf(Y_batch*Y_std, loc=m*Y_std, scale=Y_std*v**0.5), 2)
`
Because everything is already standarized shouldn't it be just:

`S_lik = np.sum(norm.logpdf(Y_batch, loc=m, scale=v**0.5), 2)
`
Maybe I'm wrong

**Comment by hughsalimbeni** [comment]
It's for comparison with methods that use the unscaled data. In the literature it's generally been the case that the results are reported on the unscaled data, so in the code it restores the original scaling. Note that the results aren't the same under the two distributions.

**Comment by BaoGenzo** [comment]
oh, I see. That solved my question, thank you.
