### ISSUE TITLE
ModuleNotFoundError: No module named 'gpflow.logdensities' in gpfow1.1.1 version

### ISSUE THREAD

**Issue by PavlosCh** [ICL-SML/Doubly-Stochastic-DGP#41]
Hi Hugh, 

When using gpflow1.1.1 I the module 'gpflow.logdensities' doesn't seem to exist and I get a ModulNotFoundError. This is corrected however if a newer gpflow version is used (i.e. 1.3). Can you confirm that gpflow1.1.1 is still the appropriate version to use? 

Thanks, 
Pavlos

**Comment by jjramsey** [comment]
I got burned by this problem as well. GPFlow 1.1.1 does *not* work with Doubly-Stochastic-DGP. I seem to be able to get GPFlow 1.3 to work, at least in the sense that I wasn't getting errors from Python.

**Comment by hughsalimbeni** [comment]
Hi sorry about this. This repo has been superseded by https://github.com/hughsalimbeni/DGPs_with_IWVI, so I'm not going to actively maintain this one and ensure compatibility.
