### ISSUE TITLE
requirements for pre release dgp-0.1

### ISSUE THREAD

**Issue by svaibhavsingh** [ICL-SML/Doubly-Stochastic-DGP#6]
It is mentioned that the pre-release version requires GPflow 0.4 but in that the name of package is changed from "GPflow" to" gpflow" and in the released version it is using GPflow (maybe some older version). Can you please share exact release version of GPflow being used for the code?

**Comment by hughsalimbeni** [comment]
Sorry about this. I'm working on the release to 1.0 at the moment, so haven't looked at the dependencies of the older version with the old version of gpflow. Since the new gpflow is so much better than the old one I think I'd rather just push into 1.0 asap. I'll do that later today.

**Comment by svaibhavsingh** [comment]
Thanks for replying. Yes GPflow 1.0 is much better. I figured that out, GPflow-0.3.9 is working fine.
