### ISSUE TITLE
Question regarding noise added in each layer.

### ISSUE THREAD

**Issue by svaibhavsingh** [ICL-SML/Doubly-Stochastic-DGP#8]
I was trying to figure out where exactly the noise is being added inside the kernel elements of each layer.

**Comment by hughsalimbeni** [comment]
There is no noise between layers, apart from a small jitter for numerical stability

**Comment by vinayakk1094** [comment]
No he's talking about the noise that is embedded into the kernel itself
while mapping from one layer to the next.... As is mentioned in your paper.
Doubly Stochastic variational inference for deep gaussian processes.

**Comment by hughsalimbeni** [comment]
I think I see what you're asking now: in the original Damianou 2013 paper there is explicit noise between layers. You can achieve exactly this model with this code with RBF + White kernel at each layer, but the inference is not equivalent. In fact, it is impossible to represent the noisy variables with inducing points (similarly with an ordinary sparse GP: if you use a RBF + White kernel with Z=X you don't get the same answer as the full rank model).

**Comment by vinayakk1094** [comment]
So , basically you are not learning the sigma_l^2 , noise variance between
two layers , mentioned in section 2 paragraph just before equation (11) in
your paper Doubly Stochastic Variational Inference for Deep Gaussian
Processes.

**Comment by mathDR** [comment]
@vinayakk1094 In the same paragraph you mention is the following:
Our method of inference does not require us to parameterize these variables separately. For notational convenience, we therefore absorb the noise into the kernel 
```knoisy(xi, xj ) = k(xi, xj )+σ2l δij``` , where ```δij``` is the Kronecker delta, and `σ2l` is the noise variance between layers.

That said, when you absorb the noise into the kernel, then, if you want a descriptive version of the noise, you must use a form like @hughsalimbeni states above:
```RBF + White kernel``` or similar.

So the simple answer to your question is, yes, the model learns the sigma_l^2 noise term between layers, but it is NOT the same noise term as in the Damianou 2013 paper, as the models are different.

**Comment by hughsalimbeni** [comment]
In the experiments in the paper we did indeed learn the sigma^2 and included a white component in the kernel for each layer. In all cases sigma^2 tended to zero (1e-6 is the minimal value), regardless of initialization. This is due to the inability of inducing points to model a white noise process posterior (this is true for the single layer SVGP model). The current code also adds jitter, however, so using a kernel without noise should be stable.
